# Generated by Django 4.2.13 on 2024-09-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='type',
            field=models.CharField(choices=[('tomato', 'Tomato'), ('cucumber', 'Cucumber'), ('rice', 'Rice')], default='tomato', max_length=20),
        ),
    ]
