# Generated by Django 4.2.13 on 2024-09-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_greenhouse_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhouse',
            name='type',
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('tomato', 'Tomato'), ('rice', 'Rice'), ('cucumber', 'Cucumber')], max_length=50),
        ),
    ]
