# Generated by Django 4.2.13 on 2024-09-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_greenhouse_type_greenhouse_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='crop_type',
            field=models.CharField(choices=[('tomato', 'Tomato'), ('rice', 'Rice'), ('cucumber', 'Cucumber')], max_length=20),
        ),
    ]
