# Generated by Django 4.2.13 on 2024-09-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_greenhouse_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='crop_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
