# Generated by Django 4.2.13 on 2024-09-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_image_document_image_path_and_more'),
        ('dashboard', '0005_alter_greenhouse_crop_type'),
    ]

    operations = [
    ]
