# Generated by Django 4.2.13 on 2024-09-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='greenhouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.greenhouse'),
        ),
    ]
