# Generated by Django 4.2.13 on 2024-09-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_image_greenhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BacterialSpot', models.FloatField()),
                ('EarlyBlight', models.FloatField()),
                ('Healthy', models.FloatField()),
                ('LateBlight', models.FloatField()),
                ('LeafMold', models.FloatField()),
                ('SeptoriaLeafSpot', models.FloatField()),
                ('SpiderMites', models.FloatField()),
                ('TargetSpot', models.FloatField()),
                ('TomatoMosaicVirus', models.FloatField()),
                ('YellowLeafCurlVirus', models.FloatField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Rice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BacterialLeafBlight', models.FloatField()),
                ('BrownSpot', models.FloatField()),
                ('Healthy', models.FloatField()),
                ('LeafBlast', models.FloatField()),
                ('LeafScald', models.FloatField()),
                ('SheathBlight', models.FloatField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Cucumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anthracnose', models.FloatField()),
                ('BacterialWilt', models.FloatField()),
                ('DownyMildew', models.FloatField()),
                ('Healthy', models.FloatField()),
                ('GummyStemBlight', models.FloatField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.greenhouse')),
            ],
        ),
    ]
