# Generated by Django 4.2.13 on 2024-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_anthracnose_cucumber_anthracnose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='anthracnose',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='bacterial_wilt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='downy_wildew',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='gummy_stem_blight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='healthy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rice',
            name='bacterial_leaf_blight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rice',
            name='brown_spot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rice',
            name='healthy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rice',
            name='leaf_blast',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rice',
            name='leaf_scald',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rice',
            name='sheath_blight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='bacterial_spot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='early_blight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='healthy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='late_blight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='leaf_mold',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='septoria_leaf_spot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='spider_mites',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='target_spot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='tomato_mosaic_virus',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='yellow_leaf_curl_virus',
            field=models.FloatField(null=True),
        ),
    ]
