# Generated by Django 4.2.13 on 2024-09-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_alter_cucumber_anthracnose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="greenhouse",
            name="total_square_units",
            field=models.FloatField(null=True),
        ),
    ]
